# Generates pretty snake animation, using @Platane's awesome snk action
name: 🐍 Generate Snake Contribution GIF
on:
  workflow_dispatch: # Manual dispatch
  schedule:
    - cron: '0 0 * * *' # Runs at 23:30 every day.
jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Generate Snake
        uses: Platane/snk@main
        with:
          github_user_name: ${{ github.ian-dubaideveloper }}
          gif_out_path: assets/github-snake.gif
          svg_out_path: assets/github-snake.svg          
      # Commit the changes
      - name: Commit files
        run: |
          git config user.email "ian.dubaideveloper@yahoo.com"
          git config user.name "ian-dubaideveloper"
          git add .
          git commit -m ":snake: Updates Snake Contribution Animation"
      # Push the changes
      - name: Push
        uses: ad-m/github-push-action@main
        with:
          github_token: ${{ secrets.BOT_GITHUB_TOKEN }}
          branch: ${{ github.ref }}
